### ISSUE TITLE
incompatibility with killbill v 20

### ISSUE THREAD

**Issue by yingque01** [SolarNetwork/killbill-easytax-plugin#1]
Hi I have been struggling for a few days with this issue and it seems like the plugin is calling some code that is not compatible with V20 of killbill 
any idea how I could locally refactor this and work around it 
java.lang.AbstractMethodError: 
org.killbill.billing.plugin.easytax.api.EasyTaxInvoicePluginApi.priorCall
(Lorg/killbill/billing/invoice/plugin/api/InvoiceContext;Ljava/lang/Iterable;)
Lorg/killbill/billing/invoice/plugin/api/PriorInvoiceResult;
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler$1.execute(ContextClassLoaderHelper.java:144)
        at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
        at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler.handleInvocation(ContextClassLoaderHelper.java:141)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
        at com.sun.proxy.$Proxy162.priorCall(Unknown Source)
        at org.killbill.billing.invoice.InvoicePluginDispatcher.priorCall(InvoicePluginDispatcher.java:89)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLockAndInputTargetDate(InvoiceDispatcher.java:525)
        at org.killbill.billing.invoice.InvoiceDispatcher.processDryRun_UPCOMING_INVOICE_Invoice(InvoiceDispatcher.java:432)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccountWithLock(InvoiceDispatcher.java:373)
        at org.killbill.billing.invoice.InvoiceDispatcher.processAccount(InvoiceDispatcher.java:295)
        at org.killbill.billing.invoice.api.user.DefaultInvoiceUserApi.triggerDryRunInvoiceGeneration(DefaultInvoiceUserApi.java:249)
        at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
        at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
        at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
        at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
        at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
        at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
        at org.killbill.billing.jaxrs.resources.InvoiceResource.generateDryRunInvoice(InvoiceResource.java:417)
        at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:69)
        at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor$1.execute(JaxRSAopModule.java:87)
        at org.killbill.billing.util.entity.dao.DBRouterUntyped.withRODBIAllowed(DBRouterUntyped.java:57)
        at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor.invoke(JaxRSAopModule.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:111)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:279)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zjayyousi** [comment]
We had the same problem, this plugin is only for K.B. version 1.8, we modified this project to work with  K.B. v 2.0, I could share the source with you, didn't have time to fork it etc.

**Comment by yingque01** [comment]
Hi thanks
I wish I had reached out earlier as I spent quite a few days on trying to
work around this
yes please share the source code change with me to allow this project to
work with KB V0.20.
Don t worry about spending time to fork it :)

**Comment by yingque01** [comment]
Hi there, I found this fork 
https://github.com/zjayyousi/killbill-easytax-plugin
If that your code ?

**Comment by zjayyousi** [comment]
yes, but just a fork of this project, the files are not updated, give me few mins

**Comment by zjayyousi** [comment]
Here you can get it from my bitbucket repo, sorry again too busy to move it here:
https://ziadbasel@bitbucket.org/ziadbasel/killbill-easytax-plugin-0.2.0.git

**Comment by yingque01** [comment]
Thanks a lot for that mate. Your version worked perfectly in KB V0.20!!! Funny enough, I made similar changes in pom.xml and my version works too now but I was stupid in that I kept copying the jar file to the wrong path in docker. So I was for days looking at that incompatibility error from the original jar !!!

In the end all good now , your help confirmed I was on the right track except for my aforementioned stupidity :)

**Comment by zjayyousi** [comment]
Glad to hear it worked for you. Please note, I removed maven release plugin since I don't need it, just an FYI.

**Comment by msqr** [comment]
Hi @yingque01, @zjayyousi, I'm glad to hear you got it all working in v0.20. If you want to submit a PR with the changes, I'd be happy to integrate them into this project.

**Comment by zjayyousi** [comment]
Hi @msqr , thank you for this nice plugin, and yes I meant to ask you if you do not mind i will do a PR soon.  Cheers

**Comment by mvalemany** [comment]
Hi, I've been trying to integrate the modified project provided by @zjayyousi in KB v0.20.14 but I can't manage to start the plugin. How did you do it?
So far these are the only approaches I've tried that make sense:

Approach 1: https://groups.google.com/d/msg/killbilling-users/9fHLOEycDUo/pYAE6NXFAAAJ
I upload and install through kpm the easytax-plugin-0.2.0.jar to my killbill docker pod, but after I restart the pod the plugin is no longer installed, so I can't start it.

Approach 2: http://docs.killbill.io/latest/userguide_kaui.html#_kpm
I try to upload the jar using the KPM plugin in kaui, but it shows the following warning "Unable to INSTALL_PLUGIN for plugin_key=dev:easytax: Aborting installation: unable to lookup plugin".

I also made some attempts using the kpm.yml file and running the "kpm install_java_plugin" before the "kpm install", but all of them were unsuccessful. I'm not sure what else can I try, could you please give me some orientation?

Thanks in advance (and thank you for your code!)

**Comment by msqr** [comment]
@mvalemany I can't speak to @zjayyousi's project and we are not using Docker. Hopefully @zjayyousi could offer pointers. Also @zjayyousi, if you did still want to put together that PR for the v0.20 support, I could work to integrate that into this project.

**Comment by mvalemany** [comment]
@msqr even if it's without Docker, could you please give me some guidance regarding the integration of the plugin?

**Comment by msqr** [comment]
I'm not sure how I installed it on our production server, e.g. `kpm` or just manually, but in the end what I have in `killbill.properties` is

```
org.killbill.osgi.bundle.install.dir=/var/lib/killbill/bundles
```

And then in `/var/lib/killbill/bundles/plugins` I have:

```
plugins/
└── java
    └── easytax-plugin
        └── 0.1.0
            └── easytax-plugin-0.1.0.jar
```

Sorry I'm a bit vague on all this, it's been more than 2 years since I deployed this and my memory has faded.

**Comment by msqr** [comment]
Closing this due to lack of activity. Additionally we at SolarNetwork are no longer using Kill Bill so will not be working on this project any more.
